markdown: rdiscount
pygments: true
navigation:
- text: Speakers
  url: /speakers
- text: Workshops
  url: /workshops
- text: Venue
  url: /venue
- text: Sponsors
  url: /sponsors
- text: Contact
  url: /contact
2012navigation:
- text:
  url: /2012/
- url: /2012/details
  text: Details
- url: /2012/speakers
  text: Speakers
- url: /2012/schedule
  text: Schedule
- url: /2012/sponsors
  text: Sponsors
- url: /2012/location
  text: Location
- url: /2012/feedback-form
  text: Feedback
speakers:
  quote: Massively scalable systems for the gaming and gambling sectors
- name: Daniel Schauenberg
  company: Etsy
  title: Software Engineer
  country: USA
  quote: Automation, documentation and simplicity are his usual tools
- name: Mike Jones
  company: Western Cape Labs
  title: Jack of all trades
  country: SA
  quote: I started out with nothing and I still have most of it left
- name: Miles Ward
  company: Amazon
  title: Evangelist
  country: USA
  quote: A decade of experience building global-scale analysis infrastructures
- name: Daniel Fiske
  company: Rightshift
  title: CEO and Founder
  country: SA
- name: Dietrich Featherston
  company: Boundary
  title: Software Engineer
  country: USA
- name: David Tinker
  company: Brandseye
  title: Title
  country: SA
- name: Neil Blakey-Milner
  company: Facebook
  title: Production Engineer
  country: USA
- name: RI Pienaar
  company: PuppetLabs
  title: Developer
  country: UK
- name: Robert Stuttaford
  company: Cognician
  country: SA
- name: Dave Humby
  company: Nomanini
  title: CTO
  country: SA
- name: Kenny Gryp
  company: Percona
  country: USA
sponsors:
  gold:
    - name: Windows Azure
      about: A rock-solid cloud platform for blue-sky thinking
    - name: RightShift
      about: Online Gambling and Casino
  silver:
    - name: Amazon
    - name: 2Go
    - name: Praekelt
    - name: RSAWeb
  bronze:
    - name: Basho
    - name: Clickatell
    - name: Brandseye
  event:
    - name: Github
    - name: Key Connections
    - name: RSAWeb




