markdown: rdiscount
pygments: true
navigation:
- text: Speakers
  url: /speakers
- text: Workshops
  url: /workshops
- text: Venue
  url: /venue
- text: Sponsors
  url: /sponsors
- text: Contact
  url: /contact
2012navigation:
- text:
  url: /2012/
- url: /2012/details
  text: Details
- url: /2012/speakers
  text: Speakers
- url: /2012/schedule
  text: Schedule
- url: /2012/sponsors
  text: Sponsors
- url: /2012/location
  text: Location
- url: /2012/feedback-form
  text: Feedback
speakers:
- name: Beat Schwegler
  company: Microsoft
  title: Platform Strategy<br />Group Director
  country: Switzerland
- name: Dale Humby
  company: Nomanini
  title: CTO
  country: SA
- name: Daniel Fiske
  company: RightShift
  title: CEO and Founder
  country: SA
  quote: Massively scalable systems for the gaming and gambling sectors
- name: Daniel Schauenberg
  company: Etsy
  title: Software Engineer
  country: USA
  quote: Automation, documentation and simplicity are his usual tools
- name: David Tinker
  company: Brandseye
  title: Lead Engineer
  country: SA
- name: Dietrich Featherston
  company: Boundary
  title: Software Engineer
  country: USA
  quote: Dropped out of school to build an awesome analytics database which powers Boundary
- name: Kenny Gryp
  title: Engineer
  company: Percona
  country: USA
- name: Mike Jones
  company: Western Cape Labs
  title: Jack of all trades
  country: SA
  quote: I started out with nothing and I still have most of it left
- name: Miles Ward
  company: Amazon
  title: Evangelist
  country: USA
  quote: A decade of experience building global-scale analysis infrastructures
- name: Neil Blakey-Milner
  company: Facebook
  title: Production Engineer
  country: USA
- name: R.I. Pienaar
  company: PuppetLabs
  title: Developer
  country: UK
- name: Robert Stuttaford
  title: CTO
  company: Cognician
  country: SA
sponsors:
  gold:
    - name: 2go
      about: Free mobile messaging serving millions of users
    - name: RightShift
      about: Social Gaming
  silver:
    - name: Amazon
    - name: Praekelt
    - name: RSAWeb
  bronze:
    - name: Basho
    - name: Brandseye
  event:
    - name: Github
    - name: Key Connections
